# Generated by Django 4.2 on 2023-04-21 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Budget du voyage')),
                ('travel_date_start', models.DateField(verbose_name='Date de Demarrage du voyage')),
                ('travel_date_end', models.DateField(verbose_name='Date de Retour du voyage')),
                ('prefered_activitties', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_inspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage.travelinspiration')),
                ('users', models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
